name: CI

on:
  push:

permissions:
  contents: read
  actions: read

jobs:
  accept:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-unknown-elf qemu-user-static

      - name: Acceptance test
        run: ./make
