name: CI

on:
  push:

permissions:
  contents: read
  actions: read

jobs:
  accept:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static bison flex

      - name: Acceptance test
        run: ./ok

      # Run scripts/setup_git_hooks.sh if this is failing.
      - name: Linting
        run: scripts/pre-commit_hook.sh && scripts/no-vcs-changes.sh
